### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ectorr** [rinze/spotify-moods#1]
Hi, im interesting to use this mood. Could you explain where or how you execute these pythons scripts?

Thanks.

**Comment by rinze** [comment]
On Thu, Apr 14, 2016 at 6:06 AM, ectorr notifications@github.com wrote:

> Hi, im interesting to use this mood. Could you explain where or how you
> execute these pythons scripts?
> 
> ​To run the `retriever.py`, just run it from the command line and add the
> following parameters:
- The first parameter is the name of the sqlite file used to store the
  results.
- All following parameters are playlist search terms.

Example: python retriever.py /path/to/file.db sad down sorrow depressed

The analysis file in R has everything hardcoded inside, you will have to
change the paths for the DB files in order for it to work.​

**Comment by ectorr** [comment]
No sabia que eras español.. No entiendo muy bien a que te refieres con el archivo sqlite para guardar los resultados.. Otra cosa que no entiendo es a que base de datos ataca y donde lo defines, es decir, de donde sacas la base de datos de Spotify ?

Gracias por la ayuda.

**Comment by rinze** [comment]
2016-04-14 10:21 GMT-04:00 ectorr notifications@github.com:

> No sabia que eras español.. No entiendo muy bien a que te refieres con el
> archivo sqlite para guardar los resultados.. Otra cosa que no entiendo es a
> que base de datos ataca y donde lo defines, es decir, de donde sacas la
> base de datos de Spotify ?
> 
> Gracias por la ayuda.
> 
> ​La base de datos de Spotify se ataca directamente usando la librería
> "spotipy". Tienes que poner tus datos de desarrollador en el archivo
> config.py (doy el config-sample.py de ejemplo, y solo hay que rellenar los
> dos primeros campos, me parece recordar).

El archivo sqlite para guardar los resultados es la base de datos local
donde irá guardado el volcado con los resultados de las búsquedas de las
distintas listas de reproducción.​

**Comment by ectorr** [comment]
He seguido los pasos que me has comentado y el resultado:

File "C:\Users\User\Desktop\spotify-moods-master\retriever.py", line
33
    print "Still getting more songs for %s" % uri
                                          ^
SyntaxError: Missing parentheses in call to 'print'

tengo que tener alguna libreria para ejecutarlo?

**Comment by rinze** [comment]
Tiene toda la pinta de que estás usando Python 3, pero el código lo desarrollé en Python 2.7. Tendrás que editar el código para cambiar los `print` de forma que sean funciones (y entonces habrá que ver si las librerías que estoy usando no dan ningún otro problema), o ejecutarlo en una versión anterior de Python.
